import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./css/style.css";
import { ApolloWrapper } from "@/components/ApolloClient/ApolloWrapper";
import ToastProvider from "@/components/Common/ToastProvider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <ApolloWrapper>
          {children}
          <ToastProvider />
        </ApolloWrapper>
      </body>
    </html>
  );
}
